#!/usr/bin/env python3
"""AerialSim - 3D aerial view simulator using CesiumJS and Google 3D Tiles.

This module provides a simulator engine that renders 3D aerial views using
Google's Photorealistic 3D Tiles via CesiumJS. It provides an interface
similar to SatSim for seamless switching between 2D and 3D renderers.
"""

import math
import os
import shutil
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
from omegaconf import DictConfig

# Disable proxy for Selenium connections to local ChromeDriver/GeckoDriver
os.environ.pop('http_proxy', None)
os.environ.pop('https_proxy', None)
os.environ.pop('HTTP_PROXY', None)
os.environ.pop('HTTPS_PROXY', None)
os.environ['no_proxy'] = 'localhost,127.0.0.1'


class Camera:
    """Camera configuration for aerial rendering."""
    
    def __init__(self, width: int, height: int, hfov: float):
        """Initialize camera.
        
        Args:
            width: Image width in pixels.
            height: Image height in pixels.
            hfov: Horizontal field of view in degrees.
        """
        self.width = width
        self.height = height
        self.hfov = hfov


class AerialSim:
    """3D Aerial view simulator using CesiumJS and Google 3D Tiles.
    
    This simulator renders aerial views using Google's Photorealistic 3D Tiles,
    providing a 3D perspective alternative to SatSim's 2D satellite imagery.
    
    The simulator uses geographic coordinates (longitude, latitude, altitude)
    and rotation angle for agent state. RGB observations are generated by
    rendering 3D tiles from the agent's viewpoint.
    """
    
    def __init__(self, config: Union[DictConfig, dict]) -> None:
        """Initialize the AerialSim engine.
        
        Args:
            config: Configuration containing:
                - FORWARD_STEP_SIZE: Step size for forward movement (meters)
                - TURN_ANGLE: Angle for turning (degrees)
                - RGB_SENSOR: RGB sensor configuration
                    - WIDTH: Image width in pixels
                    - HEIGHT: Image height in pixels
                    - HFOV: Horizontal field of view in degrees
                - AERIAL: AerialSim-specific settings (optional)
                    - API_KEY: Google 3D Tiles API key
                    - BROWSER: Browser to use (chrome/edge/firefox)
                    - HEADLESS: Whether to run in headless mode
        """
        # Parse configuration
        if isinstance(config, DictConfig):
            self._forward_step_size = getattr(config, "FORWARD_STEP_SIZE", 10.0)
            self._turn_angle = getattr(config, "TURN_ANGLE", 15.0)
            
            rgb_config = getattr(config, "RGB_SENSOR", None)
            if rgb_config:
                width = getattr(rgb_config, "WIDTH", 448)
                height = getattr(rgb_config, "HEIGHT", 448)
                hfov = getattr(rgb_config, "HFOV", 90.0)
            else:
                width, height, hfov = 448, 448, 90.0
            
            # AerialSim-specific settings
            aerial_config = getattr(config, "AERIAL", None)
            if aerial_config:
                self._api_key = getattr(aerial_config, "API_KEY", "")
                self._browser = getattr(aerial_config, "BROWSER", "chrome")
                self._headless = getattr(aerial_config, "HEADLESS", True)
            else:
                self._api_key = ""
                self._browser = "chrome"
                self._headless = True
        else:
            self._forward_step_size = config.get("FORWARD_STEP_SIZE", 10.0)
            self._turn_angle = config.get("TURN_ANGLE", 15.0)
            
            rgb_config = config.get("RGB_SENSOR", {})
            width = rgb_config.get("WIDTH", 448)
            height = rgb_config.get("HEIGHT", 448)
            hfov = rgb_config.get("HFOV", 90.0)
            
            aerial_config = config.get("AERIAL", {})
            self._api_key = aerial_config.get("API_KEY", "")
            self._browser = aerial_config.get("BROWSER", "chrome")
            self._headless = aerial_config.get("HEADLESS", True)
        
        # Initialize camera
        self._camera = Camera(width=width, height=height, hfov=hfov)
        
        # Agent state
        self._position: Optional[np.ndarray] = None  # [longitude, latitude, altitude]
        self._rotation: Optional[float] = None  # Heading in degrees (0 = North)
        
        # Ground height cache
        self._last_ground_height: Optional[float] = None
        self._last_query_pos: Optional[Tuple[float, float]] = None
        self._ground_height_threshold = 200.0  # meters
        
        # Browser state (lazy initialization)
        self._driver = None
        self._html_path: Optional[Path] = None
        self._initialized = False
        
        # Scene metadata
        self._scene_bounds: Optional[Dict[str, float]] = None
    
    @property
    def forward_step_size(self) -> float:
        """Forward step size in meters."""
        return self._forward_step_size
    
    @property
    def turn_angle(self) -> float:
        """Turn angle in degrees."""
        return self._turn_angle
    
    def load_scene(self, scene_path: str) -> None:
        """Load scene metadata.
        
        For AerialSim, this does not load actual data since we use global
        3D Tiles. Instead, it extracts scene boundary information if available.
        
        Args:
            scene_path: Path to scene file (used for extracting bounds).
        """
        # AerialSim uses global 3D tiles, no actual scene loading needed
        # We just store the scene path for reference
        self._scene_path = scene_path
        
        # Try to extract bounds from scene path if it's a GeoTIFF
        # (for compatibility, we don't actually need this)
        self._scene_bounds = None
    
    def set_agent_state(
        self,
        position: Union[List[float], np.ndarray],
        rotation: float
    ) -> None:
        """Set agent position and rotation.
        
        Args:
            position: [longitude, latitude, altitude] in degrees and meters.
            rotation: Heading in degrees (0 = North, clockwise positive).
        """
        self._position = np.array(position, dtype=np.float64)
        self._rotation = float(rotation)
        
        # Invalidate ground height cache if position changed significantly
        if self._last_query_pos is not None:
            lat_avg = (self._position[1] + self._last_query_pos[1]) / 2
            lon_diff = abs(self._position[0] - self._last_query_pos[0]) * 111000 * math.cos(math.radians(lat_avg))
            lat_diff = abs(self._position[1] - self._last_query_pos[1]) * 111000
            dist = math.sqrt(lon_diff**2 + lat_diff**2)
            
            if dist >= self._ground_height_threshold:
                self._last_ground_height = None
                self._last_query_pos = None
    
    def get_agent_state(self) -> Tuple[np.ndarray, float]:
        """Get current agent position and rotation.
        
        Returns:
            Tuple of (position, rotation) where:
                - position: [longitude, latitude, altitude] in degrees and meters
                - rotation: Heading in degrees
                
        Raises:
            RuntimeError: If agent state has not been set.
        """
        if self._position is None or self._rotation is None:
            raise RuntimeError("Agent state not initialized. Call set_agent_state() first.")
        return self._position.copy(), self._rotation
    
    def step(self, action: Union[int, str, Dict[str, Any]]) -> Dict[str, Any]:
        """Execute an action and return new observations.
        
        Args:
            action: Action to execute. Can be:
                - Action name: "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "STOP"
                - Action index: 0=STOP, 1=MOVE_FORWARD, 2=TURN_LEFT, 3=TURN_RIGHT
                - Action dict: {"action": "MOVE_FORWARD"}
        
        Returns:
            Dictionary containing RGB observation.
        """
        if self._position is None:
            raise RuntimeError("Agent state not initialized.")
        
        # Parse action
        action_name = self._parse_action(action)
        
        # Execute action
        if action_name == "MOVE_FORWARD":
            # Move forward in the direction of current heading
            heading_rad = math.radians(self._rotation)
            
            # Calculate displacement in meters
            dx = self._forward_step_size * math.sin(heading_rad)  # East
            dy = self._forward_step_size * math.cos(heading_rad)  # North
            
            # Convert to degrees (approximate)
            lat = self._position[1]
            meters_per_deg_lat = 111000
            meters_per_deg_lng = 111000 * math.cos(math.radians(lat))
            
            self._position[0] += dx / meters_per_deg_lng  # longitude
            self._position[1] += dy / meters_per_deg_lat  # latitude
            
        elif action_name == "TURN_LEFT":
            self._rotation = (self._rotation - self._turn_angle) % 360
            
        elif action_name == "TURN_RIGHT":
            self._rotation = (self._rotation + self._turn_angle) % 360
            
        elif action_name == "STOP":
            pass  # No movement
        
        return self.get_observations()
    
    def get_observations(self) -> Dict[str, Any]:
        """Get current RGB observation by rendering the view.
        
        Returns:
            Dictionary containing:
                - "rgb": RGB image as numpy array (H, W, 3) uint8
        """
        if self._position is None:
            raise RuntimeError("Agent state not initialized.")
        
        # Ensure browser is initialized
        if not self._initialized:
            self._initialize_browser()
        
        # Render and capture
        rgb = self._render_view()
        
        return {"rgb": rgb}
    
    def is_navigable(self, position: Union[List[float], np.ndarray]) -> bool:
        """Check if a position is navigable.
        
        For AerialSim with global 3D tiles, we assume all positions are navigable
        since we don't have explicit scene bounds like SatSim.
        
        Args:
            position: [longitude, latitude, altitude] to check.
            
        Returns:
            True (always navigable for global 3D tiles).
        """
        # With global 3D tiles, we don't have explicit bounds
        # In the future, we could add bounds checking based on scene metadata
        return True
    
    def close(self) -> None:
        """Close browser and cleanup resources."""
        if self._driver is not None:
            try:
                self._driver.quit()
            except Exception:
                pass
            self._driver = None
        
        if self._html_path is not None and self._html_path.exists():
            try:
                self._html_path.unlink()
            except Exception:
                pass
            self._html_path = None
        
        self._initialized = False
    
    def _parse_action(self, action: Union[int, str, Dict[str, Any]]) -> str:
        """Parse action to action name.
        
        Args:
            action: Action in various formats.
            
        Returns:
            Action name string.
        """
        if isinstance(action, dict):
            action = action.get("action", action)
        
        if isinstance(action, int):
            action_map = {0: "STOP", 1: "MOVE_FORWARD", 2: "TURN_LEFT", 3: "TURN_RIGHT"}
            return action_map.get(action, "STOP")
        
        if isinstance(action, str):
            return action.upper()
        
        return "STOP"
    
    def _initialize_browser(self) -> None:
        """Initialize the browser for rendering."""
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options as ChromeOptions
        from selenium.webdriver.chrome.service import Service as ChromeService
        from selenium.webdriver.edge.options import Options as EdgeOptions
        from selenium.webdriver.edge.service import Service as EdgeService
        from selenium.webdriver.firefox.options import Options as FirefoxOptions
        from selenium.webdriver.firefox.service import Service as FirefoxService
        
        browser = self._browser.lower()
        headless = self._headless
        
        window_size = [self._camera.width, self._camera.height]
        
        if browser == "chrome":
            options = ChromeOptions()
            if headless:
                options.add_argument("--headless")
            options.add_argument(f"--window-size={window_size[0]},{window_size[1]}")
            options.add_argument("--no-sandbox")
            options.add_argument("--disable-dev-shm-usage")
            options.add_argument("--enable-webgl")
            options.add_argument("--use-gl=angle")
            options.add_argument("--use-angle=swiftshader-webgl")
            options.add_argument("--ignore-gpu-blocklist")
            options.add_argument("--disable-extensions")
            options.add_argument("--disable-logging")
            options.add_argument("--log-level=3")
            
            import random
            debug_port = random.randint(9000, 9999)
            options.add_argument(f"--remote-debugging-port={debug_port}")
            options.add_argument("--disable-blink-features=AutomationControlled")
            options.add_experimental_option("excludeSwitches", ["enable-automation"])
            options.add_experimental_option('useAutomationExtension', False)
            
            # Find Chrome binary
            chrome_paths = ["/usr/bin/google-chrome", "/usr/bin/chromium-browser", "/opt/google/chrome/chrome"]
            for chrome_path in chrome_paths:
                if Path(chrome_path).exists():
                    options.binary_location = chrome_path
                    break
            
            # Find ChromeDriver
            chromedriver_path = None
            for path in ["/usr/bin/chromedriver", "/usr/local/bin/chromedriver", shutil.which("chromedriver")]:
                if path and (shutil.which(path) or Path(path).exists()):
                    chromedriver_path = path
                    break
            
            if chromedriver_path:
                service = ChromeService(executable_path=chromedriver_path)
                self._driver = webdriver.Chrome(service=service, options=options)
            else:
                self._driver = webdriver.Chrome(options=options)
                
        elif browser == "edge":
            options = EdgeOptions()
            if headless:
                options.add_argument("--headless")
            options.add_argument(f"--window-size={window_size[0]},{window_size[1]}")
            self._driver = webdriver.Edge(options=options)
            
        elif browser == "firefox":
            options = FirefoxOptions()
            if headless:
                options.add_argument("--headless")
            self._driver = webdriver.Firefox(options=options)
            self._driver.set_window_size(window_size[0], window_size[1])
        
        else:
            raise ValueError(f"Unsupported browser: {browser}")
        
        # Prepare and load HTML
        self._html_path = self._prepare_html()
        file_url = f"file://{self._html_path.absolute()}"
        self._driver.set_page_load_timeout(30)
        self._driver.get(file_url)
        
        # Wait for CesiumJS to initialize
        time.sleep(5)
        
        max_check_time = 15
        check_start = time.time()
        while time.time() - check_start < max_check_time:
            cesium_ready = self._driver.execute_script("""
                return typeof Cesium !== 'undefined' && 
                       typeof window.updateViewWithFOV === 'function' &&
                       typeof window.queryGroundHeightGrid === 'function';
            """)
            if cesium_ready:
                break
            time.sleep(0.5)
        
        # Set initial container size
        render_width = int(self._camera.width * 1.2)
        render_height = int(self._camera.height * 1.2)
        self._driver.set_window_size(render_width + 100, render_height + 150)
        self._driver.execute_script(f"""
            var container = document.getElementById('cesiumContainer');
            if (container) {{
                container.style.width = '{render_width}px';
                container.style.height = '{render_height}px';
            }}
            if (typeof viewer !== 'undefined') {{ viewer.resize(); }}
        """)
        time.sleep(1)
        
        self._initialized = True
    
    def _prepare_html(self) -> Path:
        """Prepare HTML template with API key.
        
        Returns:
            Path to prepared HTML file.
        """
        template_dir = Path(__file__).parent
        template_path = template_dir / "cesium_template.html"
        
        if not template_path.exists():
            raise FileNotFoundError(f"Template not found: {template_path}")
        
        with open(template_path, 'r', encoding='utf-8') as f:
            html_content = f.read()
        
        html_content = html_content.replace("{{API_KEY}}", self._api_key)
        
        temp_html_path = template_dir / f"temp_aerial_{os.getpid()}.html"
        with open(temp_html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return temp_html_path
    
    def _query_ground_height(self, lat: float, lng: float, altitude: float) -> float:
        """Query ground height at the given position.
        
        Args:
            lat: Latitude in degrees.
            lng: Longitude in degrees.
            altitude: Target altitude above ground.
            
        Returns:
            Ground height relative to ellipsoid (with safety margin).
        """
        # Check cache
        if self._last_ground_height is not None and self._last_query_pos is not None:
            lat_avg = (lat + self._last_query_pos[1]) / 2
            lon_diff = abs(lng - self._last_query_pos[0]) * 111000 * math.cos(math.radians(lat_avg))
            lat_diff = abs(lat - self._last_query_pos[1]) * 111000
            dist = math.sqrt(lon_diff**2 + lat_diff**2)
            
            if dist < self._ground_height_threshold:
                return self._last_ground_height
        
        # Load tiles at 200m for ground height query
        self._driver.execute_script(
            f"window.updateViewWithFOV({lat}, {lng}, 200, {self._rotation}, -90, 0, {self._camera.hfov});"
        )
        
        # Wait for tiles to stabilize
        max_wait = 10
        start = time.time()
        stable_count = 0
        last_tiles = 0
        
        while time.time() - start < max_wait:
            status = self._driver.execute_script("""
                return {
                    tilesLoaded: window.__lastTilesLoaded || 0,
                    tilesetReady: window.__tilesetReady || false
                };
            """)
            tiles = status.get('tilesLoaded', 0)
            if tiles == last_tiles and tiles > 0:
                stable_count += 1
                if stable_count >= 3:
                    break
            else:
                stable_count = 0
            last_tiles = tiles
            time.sleep(0.5)
        
        time.sleep(1)
        
        # Grid query
        grid_size = altitude * 2
        grid_info = self._driver.execute_script(
            f"return window.queryGroundHeightGrid({lat}, {lng}, {grid_size}, 3);"
        )
        
        if grid_info and grid_info.get('found'):
            max_height = grid_info.get('maxHeight', 0.0)
            safety_margin = 2.0
            ground_height = max_height + safety_margin
        else:
            ground_height = 0.0
        
        # Update cache
        self._last_ground_height = ground_height
        self._last_query_pos = (lng, lat)
        
        return ground_height
    
    def _render_view(self) -> np.ndarray:
        """Render the current view and return RGB image.
        
        Returns:
            RGB image as numpy array (H, W, 3) uint8.
        """
        from PIL import Image
        import io
        
        lat = self._position[1]
        lng = self._position[0]
        altitude = self._position[2]  # Height above ground
        rotation = self._rotation
        hfov = self._camera.hfov
        
        # Query ground height
        ground_height = self._query_ground_height(lat, lng, altitude)
        
        # Calculate camera height (above ellipsoid)
        adjusted_height = ground_height + altitude
        
        # Set camera view
        self._driver.execute_script(
            f"window.updateViewWithFOV({lat}, {lng}, {adjusted_height}, {rotation}, -90, 0, {hfov});"
        )
        
        # Wait for rendering to stabilize
        max_wait = 5.0
        start = time.time()
        stable_count = 0
        
        while time.time() - start < max_wait:
            status = self._driver.execute_script("""
                return window.checkTilesetStatus ? window.checkTilesetStatus() : {stable: true};
            """)
            if status.get('stable', False):
                stable_count += 1
                if stable_count >= 3:
                    break
            else:
                stable_count = 0
            time.sleep(0.3)
        
        # Set render size
        target_width = self._camera.width
        target_height = self._camera.height
        render_width = int(target_width * 1.2)
        render_height = int(target_height * 1.2)
        
        self._driver.set_window_size(render_width + 100, render_height + 150)
        self._driver.execute_script(f"""
            var container = document.getElementById('cesiumContainer');
            if (container) {{
                container.style.width = '{render_width}px';
                container.style.height = '{render_height}px';
            }}
            if (typeof viewer !== 'undefined') {{ viewer.resize(); }}
        """)
        time.sleep(0.5)
        
        # Take screenshot
        canvas = self._driver.find_element("id", "cesiumContainer")
        screenshot_bytes = canvas.screenshot_as_png
        
        # Process image
        img = Image.open(io.BytesIO(screenshot_bytes))
        actual_w, actual_h = img.size
        
        # Crop to target size
        if actual_w >= target_width and actual_h >= target_height:
            crop_left = (actual_w - target_width) // 2
            crop_top = (actual_h - target_height) // 2
            img = img.crop((crop_left, crop_top, crop_left + target_width, crop_top + target_height))
        else:
            img = img.resize((target_width, target_height), Image.Resampling.LANCZOS)
        
        # Convert to numpy array
        rgb = np.array(img.convert('RGB'), dtype=np.uint8)
        
        return rgb
