#!/usr/bin/env python3
from __future__ import annotations

"""AerialSim - 3D aerial view simulator using CesiumJS and Google 3D Tiles.

This module provides a simulator engine that renders 3D aerial views using
Google's Photorealistic 3D Tiles via CesiumJS. It provides an interface
similar to SatSim for seamless switching between 2D and 3D renderers.
"""

import atexit
import math
import os
import shutil
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from omegaconf import DictConfig

# Preserve the user's proxy configuration for remote assets (CesiumJS, Google
# 3D Tiles) while ensuring local WebDriver traffic bypasses the proxy.
for env_key in ("no_proxy", "NO_PROXY"):
    existing = os.environ.get(env_key, "")
    entries = [item.strip() for item in existing.split(",") if item.strip()]
    for host in ("localhost", "127.0.0.1"):
        if host not in entries:
            entries.append(host)
    os.environ[env_key] = ",".join(entries)


def _cfg_get(config: Union[DictConfig, dict, None], key: str, default: Any) -> Any:
    """Read a key from either an OmegaConf node or a plain dict."""
    if config is None:
        return default
    if isinstance(config, DictConfig):
        return getattr(config, key, default)
    return config.get(key, default)


class RenderValidationError(RuntimeError):
    """Raised when a render attempt is incomplete or visually invalid."""

    def __init__(
        self,
        message: str,
        *,
        candidate_rgb: Optional[np.ndarray] = None,
        metrics: Optional["ImageQualityMetrics"] = None,
        status: Optional[Dict[str, Any]] = None,
    ) -> None:
        super().__init__(message)
        self.candidate_rgb = candidate_rgb
        self.metrics = metrics
        self.status = status


@dataclass(frozen=True)
class ImageQualityMetrics:
    """Cheap image-level diagnostics used to reject obviously broken renders."""

    mean: float
    std: float
    black_frac: float
    dark_frac: float
    unique_colors: int

    @property
    def score(self) -> float:
        # High-variance, low-black images are preferred when retrying capture.
        return (
            self.std
            - 500.0 * self.black_frac
            - 150.0 * self.dark_frac
            + min(self.unique_colors / 10000.0, 20.0)
        )


class Camera:
    """Camera configuration for aerial rendering."""
    
    def __init__(self, width: int, height: int, hfov: float):
        """Initialize camera.
        
        Args:
            width: Image width in pixels.
            height: Image height in pixels.
            hfov: Horizontal field of view in degrees.
        """
        self.width = width
        self.height = height
        self.hfov = hfov


class AerialSim:
    """3D Aerial view simulator using CesiumJS and Google 3D Tiles.
    
    This simulator renders aerial views using Google's Photorealistic 3D Tiles,
    providing a 3D perspective alternative to SatSim's 2D satellite imagery.
    
    The simulator uses geographic coordinates (longitude, latitude, altitude)
    and rotation angle for agent state. RGB observations are generated by
    rendering 3D tiles from the agent's viewpoint.
    """

    _VALIDATED_API_KEYS: Dict[str, bool] = {}
    
    def __init__(self, config: Union[DictConfig, dict]) -> None:
        """Initialize the AerialSim engine.
        
        Args:
            config: Configuration containing:
                - FORWARD_STEP_SIZE: Step size for forward movement (meters)
                - TURN_ANGLE: Angle for turning (degrees)
                - RGB_SENSOR: RGB sensor configuration
                    - WIDTH: Image width in pixels
                    - HEIGHT: Image height in pixels
                    - HFOV: Horizontal field of view in degrees
                - AERIAL: AerialSim-specific settings (optional)
                    - API_KEY: Google 3D Tiles API key
                    - BROWSER: Browser to use (chrome/edge/firefox)
                    - HEADLESS: Whether to run in headless mode
        """
        self._forward_step_size = float(_cfg_get(config, "FORWARD_STEP_SIZE", 10.0))
        self._turn_angle = float(_cfg_get(config, "TURN_ANGLE", 15.0))

        rgb_config = _cfg_get(config, "RGB_SENSOR", {})
        width = int(_cfg_get(rgb_config, "WIDTH", 448))
        height = int(_cfg_get(rgb_config, "HEIGHT", 448))
        hfov = float(_cfg_get(rgb_config, "HFOV", 90.0))

        aerial_config = _cfg_get(config, "AERIAL", {})
        self._api_key = _cfg_get(aerial_config, "API_KEY", "")
        self._browser = _cfg_get(aerial_config, "BROWSER", "chrome")
        self._headless = bool(_cfg_get(aerial_config, "HEADLESS", True))
        self._runtime_root = self._resolve_optional_path(
            os.environ.get("SATNAV_AERIALSIM_RUNTIME_DIR")
            or _cfg_get(aerial_config, "RUNTIME_DIR", "")
        )
        self._chrome_user_data_dir = self._resolve_optional_path(
            os.environ.get("SATNAV_AERIALSIM_CHROME_USER_DATA_DIR")
            or _cfg_get(aerial_config, "CHROME_USER_DATA_DIR", "")
        )
        self._chrome_disk_cache_dir = self._resolve_optional_path(
            os.environ.get("SATNAV_AERIALSIM_CHROME_DISK_CACHE_DIR")
            or _cfg_get(aerial_config, "CHROME_DISK_CACHE_DIR", "")
        )
        self._chrome_crash_dumps_dir = self._resolve_optional_path(
            os.environ.get("SATNAV_AERIALSIM_CHROME_CRASH_DUMPS_DIR")
            or _cfg_get(aerial_config, "CHROME_CRASH_DUMPS_DIR", "")
        )

        # Production robustness knobs. These defaults favor correctness over
        # raw throughput because invalid frames are more expensive than retries.
        self._enable_api_preflight = bool(_cfg_get(aerial_config, "ENABLE_API_PREFLIGHT", True))
        self._api_preflight_timeout_sec = float(_cfg_get(aerial_config, "API_PREFLIGHT_TIMEOUT_SEC", 10.0))
        self._startup_ready_timeout_sec = float(_cfg_get(aerial_config, "STARTUP_READY_TIMEOUT_SEC", 20.0))
        self._tileset_ready_timeout_sec = float(_cfg_get(aerial_config, "TILESET_READY_TIMEOUT_SEC", 30.0))
        self._ground_query_timeout_sec = float(_cfg_get(aerial_config, "GROUND_QUERY_TIMEOUT_SEC", 12.0))
        self._ground_query_grid_scale = float(_cfg_get(aerial_config, "GROUND_QUERY_GRID_SCALE", 3.0))
        self._ground_query_footprint_scale = float(_cfg_get(aerial_config, "GROUND_QUERY_FOOTPRINT_SCALE", 1.5))
        self._ground_query_samples = int(_cfg_get(aerial_config, "GROUND_QUERY_SAMPLES", 5))
        if self._ground_query_samples < 3:
            self._ground_query_samples = 3
        if self._ground_query_samples % 2 == 0:
            self._ground_query_samples += 1
        self._ground_query_safety_margin_m = float(
            _cfg_get(aerial_config, "GROUND_QUERY_SAFETY_MARGIN_METERS", 5.0)
        )
        self._height_range_clearance_scale = float(
            _cfg_get(aerial_config, "HEIGHT_RANGE_CLEARANCE_SCALE", 1.0)
        )
        self._render_stable_timeout_sec = float(_cfg_get(aerial_config, "RENDER_STABLE_TIMEOUT_SEC", 8.0))
        self._stable_polls_required = int(_cfg_get(aerial_config, "STABLE_POLLS_REQUIRED", 3))
        self._status_poll_interval_sec = float(_cfg_get(aerial_config, "STATUS_POLL_INTERVAL_SEC", 0.5))
        self._capture_attempts = int(_cfg_get(aerial_config, "CAPTURE_ATTEMPTS", 4))
        self._retry_sleep_sec = float(_cfg_get(aerial_config, "RETRY_SLEEP_SEC", 1.0))
        self._restart_after_failures = int(_cfg_get(aerial_config, "RESTART_AFTER_FAILURES", 2))
        self._max_browser_restarts = int(_cfg_get(aerial_config, "MAX_BROWSER_RESTARTS", 2))
        self._strict_validation = bool(_cfg_get(aerial_config, "STRICT_VALIDATION", True))
        self._min_tiles_loaded = int(_cfg_get(aerial_config, "MIN_TILES_LOADED", 8))
        self._ground_query_min_tiles_loaded = int(_cfg_get(aerial_config, "GROUND_QUERY_MIN_TILES_LOADED", 1))
        self._allow_salvage_capture = bool(_cfg_get(aerial_config, "ALLOW_SALVAGE_CAPTURE", False))
        self._salvage_max_pending_requests = int(_cfg_get(aerial_config, "SALVAGE_MAX_PENDING_REQUESTS", 24))
        self._salvage_max_tiles_processing = int(_cfg_get(aerial_config, "SALVAGE_MAX_TILES_PROCESSING", 4))
        self._quality_min_mean = float(_cfg_get(aerial_config, "QUALITY_MIN_MEAN", 15.0))
        self._quality_min_std = float(_cfg_get(aerial_config, "QUALITY_MIN_STD", 20.0))
        self._quality_max_black_frac = float(_cfg_get(aerial_config, "QUALITY_MAX_BLACK_FRAC", 0.60))
        self._quality_max_dark_frac = float(_cfg_get(aerial_config, "QUALITY_MAX_DARK_FRAC", 0.85))
        self._quality_min_unique_colors = int(_cfg_get(aerial_config, "QUALITY_MIN_UNIQUE_COLORS", 2000))
        
        # Initialize camera
        self._camera = Camera(width=width, height=height, hfov=hfov)
        
        # Agent state
        self._position: Optional[List[float]] = None  # [longitude, latitude, altitude]
        self._rotation: Optional[float] = None  # Heading in degrees (0 = North)
        
        # Ground height cache
        self._last_ground_height: Optional[float] = None
        self._last_query_pos: Optional[Tuple[float, float]] = None
        self._last_local_height_range: float = 0.0
        self._ground_height_threshold = 200.0  # meters
        
        # Browser state (lazy initialization)
        self._driver = None
        self._html_path: Optional[Path] = None
        self._initialized = False
        self._consecutive_capture_failures = 0
        self._browser_restart_count = 0
        
        # Scene metadata
        self._scene_bounds: Optional[Dict[str, float]] = None
    
    @property
    def forward_step_size(self) -> float:
        """Forward step size in meters."""
        return self._forward_step_size
    
    @property
    def turn_angle(self) -> float:
        """Turn angle in degrees."""
        return self._turn_angle
    
    def load_scene(self, scene_path: str) -> None:
        """Load scene metadata.
        
        For AerialSim, this does not load actual data since we use global
        3D Tiles. Instead, it extracts scene boundary information if available.
        
        Args:
            scene_path: Path to scene file (used for extracting bounds).
        """
        # AerialSim uses global 3D tiles, no actual scene loading needed
        # We just store the scene path for reference
        self._scene_path = scene_path
        
        # Try to extract bounds from scene path if it's a GeoTIFF
        # (for compatibility, we don't actually need this)
        self._scene_bounds = None
    
    def set_agent_state(
        self,
        position: List[float],
        rotation: float
    ) -> None:
        """Set agent position and rotation.
        
        Args:
            position: [longitude, latitude, altitude] in degrees and meters.
            rotation: Heading in degrees (0 = North, clockwise positive).
        """
        self._position = [float(value) for value in position]
        self._rotation = float(rotation)
        
        # Invalidate ground height cache if position changed significantly
        if self._last_query_pos is not None:
            lat_avg = (self._position[1] + self._last_query_pos[1]) / 2
            lon_diff = abs(self._position[0] - self._last_query_pos[0]) * 111000 * math.cos(math.radians(lat_avg))
            lat_diff = abs(self._position[1] - self._last_query_pos[1]) * 111000
            dist = math.sqrt(lon_diff**2 + lat_diff**2)
            
            if dist >= self._ground_height_threshold:
                self._last_ground_height = None
                self._last_query_pos = None
                self._last_local_height_range = 0.0
    
    def get_agent_state(self) -> Tuple[List[float], float]:
        """Get current agent position and rotation.
        
        Returns:
            Tuple of (position, rotation) where:
                - position: [longitude, latitude, altitude] in degrees and meters
                - rotation: Heading in degrees
                
        Raises:
            RuntimeError: If agent state has not been set.
        """
        if self._position is None or self._rotation is None:
            raise RuntimeError("Agent state not initialized. Call set_agent_state() first.")
        return list(self._position), self._rotation
    
    def step(self, action: Union[int, str, Dict[str, Any]]) -> Dict[str, Any]:
        """Execute an action and return new observations.
        
        Args:
            action: Action to execute. Can be:
                - Action name: "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "STOP"
                - Action index: 0=STOP, 1=MOVE_FORWARD, 2=TURN_LEFT, 3=TURN_RIGHT
                - Action dict: {"action": "MOVE_FORWARD"}
        
        Returns:
            Dictionary containing RGB observation.
        """
        if self._position is None:
            raise RuntimeError("Agent state not initialized.")
        
        # Parse action
        action_name = self._parse_action(action)
        
        # Execute action
        if action_name == "MOVE_FORWARD":
            # Move forward in the direction of current heading
            heading_rad = math.radians(self._rotation)
            
            # Calculate displacement in meters
            dx = self._forward_step_size * math.sin(heading_rad)  # East
            dy = self._forward_step_size * math.cos(heading_rad)  # North
            
            # Convert to degrees (approximate)
            lat = self._position[1]
            meters_per_deg_lat = 111000
            meters_per_deg_lng = 111000 * math.cos(math.radians(lat))
            
            self._position[0] += dx / meters_per_deg_lng  # longitude
            self._position[1] += dy / meters_per_deg_lat  # latitude
            
        elif action_name == "TURN_LEFT":
            self._rotation = (self._rotation - self._turn_angle) % 360
            
        elif action_name == "TURN_RIGHT":
            self._rotation = (self._rotation + self._turn_angle) % 360
            
        elif action_name == "STOP":
            pass  # No movement
        
        return self.get_observations()
    
    def get_observations(self) -> Dict[str, Any]:
        """Get current RGB observation by rendering the view.
        
        Returns:
            Dictionary containing:
                - "rgb": RGB image as numpy array (H, W, 3) uint8
        """
        if self._position is None:
            raise RuntimeError("Agent state not initialized.")
        
        # Ensure browser is initialized
        if not self._initialized:
            self._initialize_browser()
        
        # Render and capture
        rgb = self._render_view()
        
        return {"rgb": rgb}
    
    def is_navigable(self, position: List[float]) -> bool:
        """Check if a position is navigable.
        
        For AerialSim with global 3D tiles, we assume all positions are navigable
        since we don't have explicit scene bounds like SatSim.
        
        Args:
            position: [longitude, latitude, altitude] to check.
            
        Returns:
            True (always navigable for global 3D tiles).
        """
        # With global 3D tiles, we don't have explicit bounds
        # In the future, we could add bounds checking based on scene metadata
        return True
    
    def close(self) -> None:
        """Close browser and cleanup resources."""
        if self._driver is not None:
            try:
                self._driver.quit()
            except Exception:
                pass
            self._driver = None
        
        if self._html_path is not None and self._html_path.exists():
            try:
                self._html_path.unlink()
            except Exception:
                pass
            self._html_path = None
        
        self._initialized = False
    
    @staticmethod
    def _resolve_optional_path(raw_value: Any) -> Optional[Path]:
        if raw_value is None:
            return None
        value = str(raw_value).strip()
        if not value:
            return None
        return Path(value).expanduser().resolve()

    @staticmethod
    def _ensure_directory(path: Optional[Path]) -> Optional[Path]:
        if path is None:
            return None
        path.mkdir(parents=True, exist_ok=True)
        return path

    def _find_chrome_binary(self) -> Optional[Path]:
        system_candidates = [
            Path("/usr/bin/google-chrome"),
            Path("/usr/bin/chromium-browser"),
            Path("/opt/google/chrome/chrome"),
        ]
        for candidate in system_candidates:
            if candidate.exists():
                return candidate
        return None

    def _find_chromedriver_binary(self) -> Optional[Path]:
        for candidate in ["/usr/bin/chromedriver", "/usr/local/bin/chromedriver", shutil.which("chromedriver")]:
            if not candidate:
                continue
            candidate_path = Path(candidate)
            if candidate_path.exists():
                return candidate_path
        return None

    def _parse_action(self, action: Union[int, str, Dict[str, Any]]) -> str:
        """Parse action to action name.
        
        Args:
            action: Action in various formats.
            
        Returns:
            Action name string.
        """
        if isinstance(action, dict):
            action = action.get("action", action)
        
        if isinstance(action, int):
            action_map = {0: "STOP", 1: "MOVE_FORWARD", 2: "TURN_LEFT", 3: "TURN_RIGHT"}
            return action_map.get(action, "STOP")
        
        if isinstance(action, str):
            return action.upper()
        
        return "STOP"
    
    def _initialize_browser(self) -> None:
        """Initialize the browser for rendering."""
        from selenium import webdriver
        from selenium.common.exceptions import TimeoutException
        from selenium.webdriver.chrome.options import Options as ChromeOptions
        from selenium.webdriver.chrome.service import Service as ChromeService
        from selenium.webdriver.edge.options import Options as EdgeOptions
        from selenium.webdriver.edge.service import Service as EdgeService
        from selenium.webdriver.firefox.options import Options as FirefoxOptions
        from selenium.webdriver.firefox.service import Service as FirefoxService
        
        browser = self._browser.lower()
        headless = self._headless
        
        self._validate_api_key_once()

        window_size = [self._camera.width, self._camera.height]
        
        if browser == "chrome":
            options = ChromeOptions()
            options.page_load_strategy = "none"
            if headless:
                options.add_argument("--headless=new")
            options.add_argument(f"--window-size={window_size[0]},{window_size[1]}")
            options.add_argument("--no-sandbox")
            options.add_argument("--disable-dev-shm-usage")
            options.add_argument("--enable-webgl")
            options.add_argument("--use-gl=angle")
            options.add_argument("--use-angle=swiftshader-webgl")
            options.add_argument("--ignore-gpu-blocklist")
            options.add_argument("--disable-extensions")
            options.add_argument("--disable-logging")
            options.add_argument("--log-level=3")

            chrome_user_data_dir = self._ensure_directory(self._chrome_user_data_dir)
            chrome_disk_cache_dir = self._ensure_directory(self._chrome_disk_cache_dir)
            chrome_crash_dumps_dir = self._ensure_directory(self._chrome_crash_dumps_dir)
            if chrome_user_data_dir is not None:
                options.add_argument(f"--user-data-dir={chrome_user_data_dir}")
            if chrome_disk_cache_dir is not None:
                options.add_argument(f"--disk-cache-dir={chrome_disk_cache_dir}")
            if chrome_crash_dumps_dir is not None:
                options.add_argument(f"--crash-dumps-dir={chrome_crash_dumps_dir}")

            options.add_argument("--remote-debugging-port=9222")
            options.add_argument("--disable-blink-features=AutomationControlled")
            options.add_experimental_option("excludeSwitches", ["enable-automation"])
            options.add_experimental_option('useAutomationExtension', False)

            chrome_binary = self._find_chrome_binary()
            if chrome_binary is not None:
                options.binary_location = str(chrome_binary)

            chromedriver_path = self._find_chromedriver_binary()
            if chromedriver_path is not None:
                service = ChromeService(executable_path=str(chromedriver_path))
                self._driver = webdriver.Chrome(service=service, options=options)
            else:
                self._driver = webdriver.Chrome(options=options)
                
        elif browser == "edge":
            options = EdgeOptions()
            options.page_load_strategy = "none"
            if headless:
                options.add_argument("--headless")
            options.add_argument(f"--window-size={window_size[0]},{window_size[1]}")
            self._driver = webdriver.Edge(options=options)
            
        elif browser == "firefox":
            options = FirefoxOptions()
            options.page_load_strategy = "none"
            if headless:
                options.add_argument("--headless")
            self._driver = webdriver.Firefox(options=options)
            self._driver.set_window_size(window_size[0], window_size[1])
        
        else:
            raise ValueError(f"Unsupported browser: {browser}")
        
        # Prepare and load HTML
        self._html_path = self._prepare_html()
        file_url = f"file://{self._html_path.absolute()}"
        self._driver.set_page_load_timeout(120)
        try:
            self._driver.get(file_url)
        except TimeoutException:
            # Cesium keeps loading scripts and tiles in the background, so a
            # traditional "fully loaded" page state is not required here.
            pass

        self._wait_for_cesium_ready()
        self._set_render_surface_size()
        self._wait_for_tileset_ready(timeout_sec=self._tileset_ready_timeout_sec)
        self._wait_for_render_ready(timeout_sec=self._startup_ready_timeout_sec)
        self._initialized = True
    
    def _prepare_html(self) -> Path:
        """Prepare HTML template with API key.
        
        Uses tempfile to ensure automatic cleanup on program exit.
        
        Returns:
            Path to prepared HTML file.
        """
        template_dir = Path(__file__).parent
        template_path = template_dir / "cesium_template.html"
        
        if not template_path.exists():
            raise FileNotFoundError(f"Template not found: {template_path}")
        
        with open(template_path, 'r', encoding='utf-8') as f:
            html_content = f.read()
        
        html_content = html_content.replace("{{API_KEY}}", self._api_key)
        
        # Use the explicit runtime root when provided so temporary HTML files
        # never spill back to the system root partition.
        temp_dir = None
        if self._runtime_root is not None:
            temp_dir = self._ensure_directory(self._runtime_root / "html")
        fd, temp_path = tempfile.mkstemp(
            suffix='.html',
            prefix='aerialsim_',
            dir=str(temp_dir) if temp_dir is not None else None,
        )
        temp_html_path = Path(temp_path)
        
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        # Register cleanup on program exit (as backup to close())
        def cleanup():
            try:
                if temp_html_path.exists():
                    temp_html_path.unlink()
            except Exception:
                pass
        atexit.register(cleanup)
        
        return temp_html_path
    
    def _query_ground_height(self, lat: float, lng: float, altitude: float) -> float:
        """Query ground height at the given position.
        
        Args:
            lat: Latitude in degrees.
            lng: Longitude in degrees.
            altitude: Target altitude above ground.
            
        Returns:
            Ground height relative to ellipsoid (with safety margin).
        """
        # Check cache
        if self._last_ground_height is not None and self._last_query_pos is not None:
            lat_avg = (lat + self._last_query_pos[1]) / 2
            lon_diff = abs(lng - self._last_query_pos[0]) * 111000 * math.cos(math.radians(lat_avg))
            lat_diff = abs(lat - self._last_query_pos[1]) * 111000
            dist = math.sqrt(lon_diff**2 + lat_diff**2)
            
            if dist < self._ground_height_threshold:
                return self._last_ground_height
        
        # Load tiles at 200m for ground height query
        self._driver.execute_script(
            f"window.updateViewWithFOV({lat}, {lng}, 200, {self._rotation}, -90, 0, {self._camera.hfov});"
        )
        try:
            self._wait_for_scene_stable(
                timeout_sec=self._ground_query_timeout_sec,
                min_tiles_loaded=self._ground_query_min_tiles_loaded,
            )
        except RenderValidationError as exc:
            if not self._is_status_ready_for_ground_query(exc.status):
                raise
        
        # Query a larger neighborhood than the exact camera location. In dense
        # downtown scenes, the camera can clip into a nearby skyscraper if we
        # only sample the center point or a very small grid.
        footprint_meters = 2.0 * max(altitude, 1.0) * math.tan(math.radians(self._camera.hfov) / 2.0)
        grid_size = max(
            altitude * self._ground_query_grid_scale,
            footprint_meters * self._ground_query_footprint_scale,
        )
        grid_info = self._driver.execute_script(
            f"return window.queryGroundHeightGrid({lat}, {lng}, {grid_size}, {self._ground_query_samples});"
        )
        
        if grid_info and grid_info.get('found'):
            max_height = grid_info.get('maxHeight', 0.0)
            min_height = grid_info.get('minHeight', max_height)
            self._last_local_height_range = max(0.0, max_height - min_height)
            ground_height = max_height + self._ground_query_safety_margin_m
        else:
            ground_height = 0.0
            self._last_local_height_range = 0.0
        
        # Update cache
        self._last_ground_height = ground_height
        self._last_query_pos = (lng, lat)
        
        return ground_height
    
    def _render_view(self) -> np.ndarray:
        """Render the current view and return RGB image.
        
        Returns:
            RGB image as numpy array (H, W, 3) uint8.
        """
        last_error: Optional[str] = None
        best_candidate: Optional[Tuple[np.ndarray, ImageQualityMetrics]] = None
        self._browser_restart_count = 0

        for attempt_idx in range(self._capture_attempts):
            try:
                rgb = self._render_view_once()
                self._consecutive_capture_failures = 0
                return rgb
            except Exception as exc:
                last_error = f"{type(exc).__name__}: {exc}"
                if (
                    isinstance(exc, RenderValidationError)
                    and exc.candidate_rgb is not None
                    and exc.metrics is not None
                ):
                    if best_candidate is None or exc.metrics.score > best_candidate[1].score:
                        best_candidate = (exc.candidate_rgb, exc.metrics)
                self._consecutive_capture_failures += 1
                restart_browser = self._should_restart_browser(exc)
                if attempt_idx < self._capture_attempts - 1:
                    self._recover_from_capture_failure(restart_browser=restart_browser, reason=last_error)
                    continue

        if not self._strict_validation and best_candidate is not None:
            return best_candidate[0]

        raise RuntimeError(
            "AerialSim failed to produce a valid frame after "
            f"{self._capture_attempts} attempts. Last error: {last_error}"
        )

    def _render_view_once(self) -> np.ndarray:
        """Render a single validated frame or raise RenderValidationError."""
        from PIL import Image
        import io

        lat = self._position[1]
        lng = self._position[0]
        altitude = self._position[2]  # Height above ground
        rotation = self._rotation
        hfov = self._camera.hfov
        
        # Query ground height
        ground_height = self._query_ground_height(lat, lng, altitude)
        
        # Raise the camera above dense high-rise neighborhoods. Without this,
        # top-down views can clip into nearby skyscrapers or show extreme wall
        # perspective that is unusable for drone-style supervision.
        clearance = max(
            altitude,
            self._last_local_height_range * self._height_range_clearance_scale,
        )

        # Calculate camera height (above ellipsoid)
        adjusted_height = ground_height + clearance

        # Ensure the container size is stable before updateViewWithFOV computes
        # the projection matrix from the current aspect ratio.
        self._set_render_surface_size()
        target_width = self._camera.width
        target_height = self._camera.height

        # Set camera view
        self._driver.execute_script(
            f"window.updateViewWithFOV({lat}, {lng}, {adjusted_height}, {rotation}, -90, 0, {hfov});"
        )
        try:
            status = self._wait_for_scene_stable(
                timeout_sec=self._render_stable_timeout_sec,
                min_tiles_loaded=self._min_tiles_loaded,
            )
        except RenderValidationError as exc:
            if self._can_salvage_capture_from_status(exc.status):
                status = exc.status
            else:
                raise
        
        # Take screenshot
        canvas = self._driver.find_element("id", "cesiumContainer")
        screenshot_bytes = canvas.screenshot_as_png
        
        # Process image
        img = Image.open(io.BytesIO(screenshot_bytes))
        actual_w, actual_h = img.size
        
        # Crop to target size
        if actual_w >= target_width and actual_h >= target_height:
            crop_left = (actual_w - target_width) // 2
            crop_top = (actual_h - target_height) // 2
            img = img.crop((crop_left, crop_top, crop_left + target_width, crop_top + target_height))
        else:
            img = img.resize((target_width, target_height), Image.Resampling.LANCZOS)
        
        # Convert to numpy array
        import numpy as np
        rgb = np.array(img.convert('RGB'), dtype=np.uint8)
        metrics = self.compute_image_quality_metrics(rgb)
        quality_reasons = self._get_quality_failure_reasons(metrics, status)
        if quality_reasons:
            raise RenderValidationError(
                "Rejected invalid aerial frame: "
                + "; ".join(quality_reasons)
                + f" | metrics={self._format_metrics(metrics)}"
                + f" | status={self._format_status(status)}",
                candidate_rgb=rgb,
                metrics=metrics,
            )

        return rgb

    @staticmethod
    def compute_image_quality_metrics(rgb) -> ImageQualityMetrics:
        """Compute cheap image statistics for render validation."""
        import numpy as np

        gray = rgb.mean(axis=2)
        black_frac = float((gray < 8).mean())
        dark_frac = float((gray < 20).mean())
        unique_colors = int(len(np.unique(rgb.reshape(-1, 3), axis=0)))
        return ImageQualityMetrics(
            mean=float(rgb.mean()),
            std=float(rgb.std()),
            black_frac=black_frac,
            dark_frac=dark_frac,
            unique_colors=unique_colors,
        )

    def _get_quality_failure_reasons(
        self,
        metrics: ImageQualityMetrics,
        status: Optional[Dict[str, Any]] = None,
    ) -> List[str]:
        """Return human-readable reasons why a frame should be rejected."""
        reasons: List[str] = []
        if metrics.black_frac > self._quality_max_black_frac:
            reasons.append(
                f"black_frac={metrics.black_frac:.3f} > {self._quality_max_black_frac:.3f}"
            )
        if metrics.dark_frac > self._quality_max_dark_frac:
            reasons.append(
                f"dark_frac={metrics.dark_frac:.3f} > {self._quality_max_dark_frac:.3f}"
            )
        if metrics.mean < self._quality_min_mean:
            reasons.append(f"mean={metrics.mean:.2f} < {self._quality_min_mean:.2f}")
        if metrics.std < self._quality_min_std:
            reasons.append(f"std={metrics.std:.2f} < {self._quality_min_std:.2f}")
        if metrics.unique_colors < self._quality_min_unique_colors:
            reasons.append(
                f"unique_colors={metrics.unique_colors} < {self._quality_min_unique_colors}"
            )

        if status is not None:
            if not status.get("ready", False):
                reasons.append("tileset not ready")
            if not status.get("render_ready", False):
                reasons.append("render not ready")
            if int(status.get("tiles_loaded", 0)) < self._min_tiles_loaded:
                reasons.append(
                    f"tiles_loaded={int(status.get('tiles_loaded', 0))} < {self._min_tiles_loaded}"
                )
            if int(status.get("pending_requests", 0)) > 0:
                reasons.append(
                    f"pending_requests={int(status.get('pending_requests', 0))} > 0"
                )
            if int(status.get("tiles_processing", 0)) > 0:
                reasons.append(
                    f"tiles_processing={int(status.get('tiles_processing', 0))} > 0"
                )
            if status.get("tileset_error"):
                reasons.append(f"tileset_error={status['tileset_error']}")

        return reasons

    def _validate_api_key_once(self) -> None:
        """Fail fast if the configured Google 3D Tiles key is unusable."""
        if not self._api_key:
            raise RuntimeError("AerialSim API_KEY is empty.")
        if not self._enable_api_preflight:
            return
        if self._api_key in self._VALIDATED_API_KEYS:
            return

        request = Request(
            f"https://tile.googleapis.com/v1/3dtiles/root.json?key={self._api_key}",
            headers={"User-Agent": "SatNav-AerialSim/1.0"},
        )
        try:
            with urlopen(request, timeout=self._api_preflight_timeout_sec) as response:
                status_code = getattr(response, "status", response.getcode())
                if status_code != 200:
                    raise RuntimeError(
                        f"Google 3D Tiles preflight returned HTTP {status_code}."
                    )
                response.read(256)
        except HTTPError as exc:
            raise RuntimeError(
                f"Google 3D Tiles preflight failed with HTTP {exc.code}. "
                "Check API key, quota, and API enablement."
            ) from exc
        except URLError as exc:
            raise RuntimeError(
                "Google 3D Tiles preflight failed. Check network connectivity and proxy settings."
            ) from exc

        self._VALIDATED_API_KEYS[self._api_key] = True

    def _wait_for_cesium_ready(self) -> None:
        """Wait until Cesium and helper JS functions are available."""
        deadline = time.time() + self._startup_ready_timeout_sec
        while time.time() < deadline:
            cesium_ready = self._driver.execute_script("""
                return typeof Cesium !== 'undefined' &&
                       typeof window.updateViewWithFOV === 'function' &&
                       typeof window.queryGroundHeightGrid === 'function' &&
                       typeof window.checkTilesetStatus === 'function' &&
                       typeof window.forceRender === 'function';
            """)
            if cesium_ready:
                return
            time.sleep(self._status_poll_interval_sec)
        raise RuntimeError("Timed out waiting for Cesium runtime helpers to initialize.")

    def _wait_for_tileset_ready(self, timeout_sec: float) -> Dict[str, Any]:
        """Wait until the tileset manifest is ready and root metadata is loaded."""
        deadline = time.time() + timeout_sec
        last_status: Optional[Dict[str, Any]] = None
        self._force_render()
        while time.time() < deadline:
            last_status = self._get_tileset_status()
            if last_status.get("tileset_error") and not last_status.get("ready", False):
                raise RenderValidationError(
                    f"Tileset failed to initialize: {last_status['tileset_error']}"
                )
            if last_status.get("ready", False):
                return last_status
            self._force_render()
            time.sleep(self._status_poll_interval_sec)
        raise RenderValidationError(
            "Timed out waiting for Google 3D Tiles to become ready. "
            f"Last status: {self._format_status(last_status)}"
        )

    def _wait_for_render_ready(self, timeout_sec: float) -> Dict[str, Any]:
        """Wait until Cesium has rendered at least one frame."""
        deadline = time.time() + timeout_sec
        last_status: Optional[Dict[str, Any]] = None
        self._force_render()
        while time.time() < deadline:
            last_status = self._get_tileset_status()
            if last_status.get("render_ready", False):
                return last_status
            self._force_render()
            time.sleep(self._status_poll_interval_sec)
        raise RenderValidationError(
            "Timed out waiting for the first Cesium render. "
            f"Last status: {self._format_status(last_status)}"
        )

    def _wait_for_scene_stable(
        self,
        timeout_sec: float,
        min_tiles_loaded: int,
    ) -> Dict[str, Any]:
        """Wait until the current view has enough loaded tiles and no pending work."""
        deadline = time.time() + timeout_sec
        stable_polls = 0
        last_status: Optional[Dict[str, Any]] = None
        self._force_render()
        while time.time() < deadline:
            last_status = self._get_tileset_status()
            if last_status.get("tileset_error") and not last_status.get("ready", False):
                raise RenderValidationError(
                    f"Tileset error before capture: {last_status['tileset_error']}"
                )

            status_ok = self._is_status_ready_for_capture(
                last_status,
                min_tiles_loaded=min_tiles_loaded,
            )
            if status_ok:
                stable_polls += 1
                if stable_polls >= self._stable_polls_required:
                    return last_status
            else:
                stable_polls = 0

            self._force_render()
            time.sleep(self._status_poll_interval_sec)

        raise RenderValidationError(
            "Timed out waiting for a stable 3D Tiles render. "
            f"Last status: {self._format_status(last_status)}",
            status=last_status,
        )

    def _set_render_surface_size(self) -> None:
        """Resize the browser window and Cesium container, then request a render."""
        target_width = self._camera.width
        target_height = self._camera.height
        render_width = int(target_width * 1.2)
        render_height = int(target_height * 1.2)
        self._driver.set_window_size(render_width + 100, render_height + 150)
        self._driver.execute_script(f"""
            var container = document.getElementById('cesiumContainer');
            if (container) {{
                container.style.width = '{render_width}px';
                container.style.height = '{render_height}px';
            }}
            if (typeof window.forceRender === 'function') {{
                window.forceRender();
            }} else if (typeof viewer !== 'undefined') {{
                window.__renderReady = false;
                viewer.resize();
                viewer.scene.requestRender();
            }}
        """)
        time.sleep(self._status_poll_interval_sec)

    def _force_render(self) -> None:
        """Ask Cesium to produce a fresh frame in requestRenderMode."""
        self._driver.execute_script("""
            if (typeof window.forceRender === 'function') {
                window.forceRender();
            } else if (typeof viewer !== 'undefined') {
                window.__renderReady = false;
                viewer.resize();
                viewer.scene.requestRender();
            }
        """)

    def _get_tileset_status(self) -> Dict[str, Any]:
        """Return a normalized status dict from the Cesium page."""
        status = self._driver.execute_script("""
            if (typeof window.checkTilesetStatus !== 'function') {
                return {};
            }
            return window.checkTilesetStatus();
        """) or {}

        return {
            "ready": bool(status.get("ready", False)),
            "progress": float(status.get("progress", 0.0) or 0.0),
            "stable": bool(status.get("stable", False)),
            "tiles_loaded": int(status.get("tilesLoaded", 0) or 0),
            "frames_since_last_check": int(status.get("framesSinceLastCheck", 0) or 0),
            "pending_requests": int(status.get("pendingRequests", 0) or 0),
            "tiles_processing": int(status.get("tilesProcessing", 0) or 0),
            "selected_tiles": int(status.get("selectedTiles", 0) or 0),
            "total_tiles": int(status.get("totalTiles", 0) or 0),
            "render_ready": bool(status.get("renderReady", False)),
            "tileset_error": str(status.get("tilesetError", "") or ""),
            "tile_failed_count": int(status.get("tileFailedCount", 0) or 0),
            "last_tile_failed_message": str(status.get("lastTileFailedMessage", "") or ""),
        }

    def _is_status_ready_for_capture(
        self,
        status: Dict[str, Any],
        min_tiles_loaded: int,
    ) -> bool:
        """Pure status gate before paying the cost of image capture."""
        return (
            status.get("ready", False)
            and status.get("render_ready", False)
            and status.get("stable", False)
            and int(status.get("tiles_loaded", 0)) >= int(min_tiles_loaded)
            and int(status.get("pending_requests", 0)) == 0
            and int(status.get("tiles_processing", 0)) == 0
        )

    def _is_status_ready_for_ground_query(self, status: Optional[Dict[str, Any]]) -> bool:
        if not status:
            return False
        return (
            status.get("ready", False)
            and status.get("render_ready", False)
            and not status.get("tileset_error")
            and int(status.get("tiles_loaded", 0)) >= self._ground_query_min_tiles_loaded
            and int(status.get("pending_requests", 0)) <= max(self._salvage_max_pending_requests, 32)
            and int(status.get("tiles_processing", 0)) <= max(self._salvage_max_tiles_processing, 8)
        )

    def _can_salvage_capture_from_status(self, status: Optional[Dict[str, Any]]) -> bool:
        """Fallback gate for screenshots that look visually ready but still stream tiles."""
        if not self._allow_salvage_capture or not status:
            return False
        return (
            status.get("ready", False)
            and status.get("render_ready", False)
            and not status.get("tileset_error")
            and int(status.get("tiles_loaded", 0)) >= self._min_tiles_loaded
            and int(status.get("pending_requests", 0)) <= self._salvage_max_pending_requests
            and int(status.get("tiles_processing", 0)) <= self._salvage_max_tiles_processing
        )

    def _should_restart_browser(self, exc: Exception) -> bool:
        """Decide whether the current browser session is worth keeping."""
        if self._browser_restart_count >= self._max_browser_restarts:
            return False
        if not isinstance(exc, RenderValidationError):
            return True
        return self._consecutive_capture_failures >= self._restart_after_failures

    def _recover_from_capture_failure(self, restart_browser: bool, reason: str) -> None:
        """Recover from a failed capture attempt before retrying."""
        if restart_browser:
            self.close()
            self._browser_restart_count += 1
            self._initialize_browser()
        else:
            time.sleep(self._retry_sleep_sec)
            self._force_render()

    @staticmethod
    def _format_metrics(metrics: ImageQualityMetrics) -> str:
        return (
            f"mean={metrics.mean:.2f}, std={metrics.std:.2f}, "
            f"black_frac={metrics.black_frac:.4f}, dark_frac={metrics.dark_frac:.4f}, "
            f"unique_colors={metrics.unique_colors}"
        )

    @staticmethod
    def _format_status(status: Optional[Dict[str, Any]]) -> str:
        if not status:
            return "<no-status>"
        return (
            f"ready={status.get('ready')} render_ready={status.get('render_ready')} "
            f"stable={status.get('stable')} tiles_loaded={status.get('tiles_loaded')} "
            f"pending={status.get('pending_requests')} processing={status.get('tiles_processing')} "
            f"tile_failed_count={status.get('tile_failed_count')} "
            f"tileset_error={status.get('tileset_error')!r}"
        )
